# Generated by Django 2.2.4 on 2019-10-19 17:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('address_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('SU', 'Super_user'), ('GU', 'General_user'), ('ST', 'Staff')], default='GU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Etc', 'Etc')], max_length=3, null=True)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.URLField(blank=True, max_length=255, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('register_num', models.CharField(blank=True, max_length=15, null=True)),
                ('illness', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('allergy', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('prefer_ingredient', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('representative', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
