# Generated by Django 2.2.4 on 2019-10-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191020_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='representative',
            field=models.BooleanField(default=False),
        ),
    ]
